### PR TITLE
Delete setup_android.py

### PR DESCRIPTION
**Pull request by crazyhappygame**
This file is not needed with latest android SDK

THIS PROJECT IS IN DEVELOPMENT MODE. Any pull requests should merge to branch `dev`, otherwise will be rejected immediately.

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by aismann** [comment]
Which SDK version?

**Comment by crazyhappygame** [comment]
Sorry it is about Android Gradle Plugin
https://developer.android.com/studio/projects/install-ndk#install_ndk_and_cmake_automatically

> Android Gradle Plugin 4.2.0+ can automatically install the required NDK and CMake the first time you build your project

**Comment by aismann** [comment]
Need we also an Info on readme about this gradle plugin version?

**Comment by crazyhappygame** [comment]
There is
```
  4. Start Android Studio and Open [Tools][SDKManager], then switch to ```SDK Tools```, check the ```Show Package Details```, choose the following tools and click the button ```Apply``` to install them:  
     * Android SDK Platform 33  
     * Android Gradle Plugin (AGP) 7.2.2  
     * Android SDK Build-Tools 30.0.3 match with AGP
     * Gradle 7.4.2  
     * NDK r23c+  
     * CMake 3.22.1+  
```
In the case above is not installed, Android Gradle Plugin 4.2.0+  will install automatically

**Comment by aismann** [comment]
@crazyhappygame 
Thanks for your PR.

**Pull request merged**
