### PR TITLE
Compile fix for VS2022 17.8

### LINKED ISSUE #1435: Compilation error when using VS2022 v17.8.0
- axmol version:
- devices test on:
- developing environments
   - NDK version: r23c
   - Xcode version: 14.2
   - Visual Studio: 
      - VS version: 2022 (17.8.0)
      - MSVC version: 1929, 1934, 19.35, 19.36, 19.37
      - Windows SDK version: 10.0.22621.0
   - cmake version: 
Steps to Reproduce:

image

It seems that `_String_iter_types` has been updated to remove redundant template parameters:
https://github.com/microsoft/STL/commit/45111bbc67c58fd3a5d7e172f8eb29c80c750ff6#diff-47339b57101941628ad9f2c5369af8928f218a6716d304e14b7480dcc84392f6

It seems to work if the code in `ntcvt.hpp` is changed from this:
```
namespace detail
{
// different with resize, not all of fill new memory with '\0'
template <class _Elem, class _Traits = std::char_traits<_Elem>,
          class _Alloc = std::allocator<_Elem>>
class intrusive_string : public std::basic_string<_Elem, _Traits, _Alloc>
{
public:
#if _MSC_VER >= 1920 // VS2019+
  using _Alty        = std::_Rebind_alloc_t<_Alloc, _Elem>;
  using _Alty_traits = std::allocator_traits<_Alty>;

  using _Scary_val = std::_String_val<
      std::conditional_t<std::_Is_simple_alloc_v<_Alty>, std::_Simple_types<_Elem>,
                         std::_String_iter_types<
                             _Elem, typename _Alty_traits::size_type,
                             typename _Alty_traits::difference_type, typename _Alty_traits::pointer,
                             typename _Alty_traits::const_pointer, _Elem&, const _Elem&>>>;
#endif
```
to this:
```
namespace detail
{
// different with resize, not all of fill new memory with '\0'
template <class _Elem, class _Traits = std::char_traits<_Elem>,
          class _Alloc = std::allocator<_Elem>>
class intrusive_string : public std::basic_string<_Elem, _Traits, _Alloc>
{
public:
#if _MSC_VER >= 1935 // VS2022 v17.8.0+
  using _Alty        = std::_Rebind_alloc_t<_Alloc, _Elem>;
  using _Alty_traits = std::allocator_traits<_Alty>;

  using _Scary_val = std::_String_val<
      std::conditional_t<std::_Is_simple_alloc_v<_Alty>, std::_Simple_types<_Elem>,
                         std::_String_iter_types<
                             _Elem, typename _Alty_traits::size_type,
                             typename _Alty_traits::difference_type, typename _Alty_traits::pointer,
                             typename _Alty_traits::const_pointer>>>;
#elif _MSC_VER >= 1920 // VS2019+
  using _Alty        = std::_Rebind_alloc_t<_Alloc, _Elem>;
  using _Alty_traits = std::allocator_traits<_Alty>;

  using _Scary_val = std::_String_val<
      std::conditional_t<std::_Is_simple_alloc_v<_Alty>, std::_Simple_types<_Elem>,
                         std::_String_iter_types<
                             _Elem, typename _Alty_traits::size_type,
                             typename _Alty_traits::difference_type, typename _Alty_traits::pointer,
                             typename _Alty_traits::const_pointer, _Elem&, const _Elem&>>>;
#endif
```

### PR DESCRIPTION
**Pull request by rh101**
Which branch your pull-request should merge into?

- `dev`: Current 2.x BugFixs or Features

## Describe your changes
Fix to compilation on VS2022 17.8.0

## Issue ticket number and link
#1435 

## Checklist before requesting a review
-  [x] I have performed a self-review of my code.
-  [ ] If it is a core feature, I have added thorough tests.
-  [x] I have checked readme and add important infos to this PR (if it needed).
-  [ ] I have added/adapted some tests too.

### CODE REVIEW

**Comment by rh101** [comment]
Looks like I need to use a better pre-processor check than `#if _MSC_VER >= 1935`.

**Comment by rh101** [comment]
If `MSC_VER >= 1938` doesn't work, then this should: `_MSC_FULL_VER >= 193833130`

**Comment by halx99** [comment]
Maybe better:
```cpp
if _MSC_VER >= 1920 // VS2019+
  using _Alty        = std::_Rebind_alloc_t<_Alloc, _Elem>;
  using _Alty_traits = std::allocator_traits<_Alty>;

  using _Scary_val = std::_String_val<
      std::conditional_t<std::_Is_simple_alloc_v<_Alty>, std::_Simple_types<_Elem>,
                         std::_String_iter_types<
                             _Elem, typename _Alty_traits::size_type,
                             typename _Alty_traits::difference_type, typename _Alty_traits::pointer,
#if _MSC_VER < 1938
                             typename _Alty_traits::const_pointer, _Elem&, const _Elem&>>>;
#else //  VS2022 17.8.0+
                             typename _Alty_traits::const_pointer>>>;
#endif
```

**Comment by halx99** [comment]
And comment on file header, thanks:
```cpp
// v1.0.1 add vs2022 17.8.0 support
// v1.0.0 works on vs2010 to vs2022 17.7.x
```

**Comment by aismann** [comment]
Please same PR for axmol 1.x

**Pull request merged**
