### PR TITLE
Fix for missing scripts and resources in lua tests project

### LINKED ISSUE #1303: HelloLua/lua_tests build arm64 osx app does not launch
- axmol version: 1.x
- devices test on: Mac Studio Apple M2 Max 
- developing environments
   - Xcode version: 14.3.1
   - cmake version: 3.27.1
Steps to Reproduce:

1. Create project with `pwsh build.ps1 -p osx -a arm64`
2. The project can compile successfully but fail to run
3. The following error message appears

Details

Could not launch “HelloLua”
Domain: IDELaunchErrorDomain
Code: 20
Recovery Suggestion: The LaunchServices launcher has returned an error. Please check the system logs for the underlying cause of the error.
User Info: {
    DVTErrorCreationDateKey = "2023-08-23 07:30:06 +0000";
    DVTRadarComponentKey = 968756;
    IDERunOperationFailingWorker = IDELaunchServicesLauncher;
}
--
The operation couldn’t be completed. Launch failed.
Domain: RBSRequestErrorDomain
Code: 5
Failure Reason: Launch failed.
--
Launchd job spawn failed
Domain: NSPOSIXErrorDomain
Code: 153
--

Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "Mac14,13";
    "device_osBuild" = "13.5.1 (22G90)";
    "device_platform" = "com.apple.platform.macosx";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 34;
    "operation_errorCode" = 20;
    "operation_errorDomain" = IDELaunchErrorDomain;
    "operation_errorWorker" = IDELaunchServicesLauncher;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.macosx";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "macosx13.3";
    "sdk_osVersion" = "13.3";
    "sdk_variant" = macos;
}
--

System Information

macOS Version 13.5.1 (Build 22G90)
Xcode 14.3.1 (21815) (Build 14E300c)
Timestamp: 2023-08-23T15:30:06+08:00

### PR DESCRIPTION
**Pull request by rh101**
Which branch your pull-request should merge into?

- `1.x`: 1.x BugFixs

## Describe your changes

Removed linker settings that were causing arm64 builds to now work on MacOS.

Resources and platform scripts for the LUA tests project are now set up correctly through the cmake script.  Note that this issue affected both Apple and Windows builds.

## Issue ticket number and link
#1303 

## Checklist before requesting a review
-  [x] I have performed a self-review of my code.
-  [ ] If it is a core feature, I have added thorough tests.
-  [x] I have checked readme and add important infos to this PR (if it needed).
-  [ ] I have added/adapted some tests too.

### CODE REVIEW

**Comment by rh101** [comment]
@halx99 I'm not too sure about the scripts and resources fix. 

I don't understand this check:
`if (NOT _AX_TOP_LEVEL_APP)`

When I changed it to this, the projects worked:
`if (_AX_TOP_LEVEL_APP)`

But, the issue is that I'm not sure if that is the correct fix.  The engine scripts were not being copied to the output correctly on both Apple and Windows builds.  

Also, the Windows cmake section creates a symbolic link named "res" to the "cpp-tests/Contents" folder, but it doesn't do so on other platforms.

**Comment by halx99** [comment]
> @halx99 I'm not too sure about the scripts and resources fix.
> 
> I don't understand this check: `if (NOT _AX_TOP_LEVEL_APP)`
> 
> When I changed it to this, the projects worked: `if (_AX_TOP_LEVEL_APP)`
> 
> But, the issue is that I'm not sure if that is the correct fix. The engine scripts were not being copied to the output correctly on both Apple and Windows builds.
> 
> Also, the Windows cmake section creates a symbolic link named "res" to the "cpp-tests/Contents" folder, but it doesn't do so on other platforms.

For tests in axmol, it's ok, the check is for project outside of axmol engine

**Comment by rh101** [comment]
> For tests in axmol, it's ok, the check is for project outside of axmol engine

Thanks for clarifying that.  The lua template hasn't been changed, so it is still `if (NOT _AX_TOP_LEVEL_APP)`, which I now know is correct.

**Comment by halx99** [comment]
> > For tests in axmol, it's ok, the check is for project outside of axmol engine
> 
> Thanks for clarifying that. The lua template hasn't been changed, so it is still `if (NOT _AX_TOP_LEVEL_APP)`, which I now know is correct.

seems the lua-tests change incorrect, when build in engine, the _AX_TOP_LEVEL_APP=FALSE, needs sync lua scripts from engine to lua-tests Content/src/

**Comment by halx99** [comment]
And, due to lua-tests share cpp-tests resources, I think the top level check can remove, alwasy regard as `FALSE`

**Comment by rh101** [comment]
> > > For tests in axmol, it's ok, the check is for project outside of axmol engine
> > 
> > 
> > Thanks for clarifying that. The lua template hasn't been changed, so it is still `if (NOT _AX_TOP_LEVEL_APP)`, which I now know is correct.
> 
> seems the lua-tests change incorrect, when build in engine, the _AX_TOP_LEVEL_APP=FALSE, needs sync lua scripts from engine to lua-tests Content/src/

Should I just get rid of the conditional statement if the code is required both _AX_TOP_LEVEL_APP true and false?

**Comment by rh101** [comment]
> And, due to lua-tests share cpp-tests resources, I think the top level check can remove, alwasy regard as `FALSE`

All good, I'll fix that now.

**Comment by halx99** [comment]
> And, due to lua-tests share cpp-tests resources, it no chance copy to outside as unique project to run, so I think the top level check can remove, alwasy regard as `FALSE`

**Comment by halx99** [comment]
all `_AX_TOP_LEVEL_APP` occurrences in lua-tests CMakeLists.txt can be removed

**Comment by rh101** [comment]
> all `_AX_TOP_LEVEL_APP` occurrences in lua-tests CMakeLists.txt can be removed

No problem, I'll change it now.

**Review by halx99 — APPROVED** [review]

**Pull request merged**
