### PR TITLE
Add missing include

### PR DESCRIPTION
**Pull request by smilediver**
Adds missing include

### CODE REVIEW

**Comment by halx99** [comment]
for which macro ?

**Comment by rh101** [comment]
> for which macro ?

My mistake, since I moved `void set(const float* array)` from `Vec4.cpp` to `Vec4.h`, and it's using the `GP_ASSERT` macro in the body of that function.  Strange that it didn't throw a compilation error in the build.

**Comment by halx99** [comment]
pch, I guess

**Comment by smilediver** [comment]
Yup, it's for `GP_ASSERT`. We include individual headers, so we will catch issues like these.

**Pull request merged**
