### PR TITLE
Fix undeclared identifier errors

### PR DESCRIPTION
**Pull request by rh101**
Which branch your pull-request should merge into?

- `dev`: Current 2.x BugFixs or Features

## Describe your changes
Use `IFileStream::Mode` instead of `FileStream::Mode` to fix undeclared identifier compilation errors (for arm64 on M1 hardware). 

## Checklist before requesting a review
-  [x] I have performed a self-review of my code.
-  [ ] If it is a core feature, I have added thorough tests.
-  [x] I have checked readme and add important infos to this PR (if it needed).
-  [ ] I have added/adapted some tests too.

### CODE REVIEW

**Comment by halx99** [comment]
Would be better?
```cpp
class FileStream : public IFileStream {
public:
   using IFileStream::Mode;
};
```

**Comment by rh101** [comment]
> Would be better?
> 
> ```c++
> class FileStream : public IFileStream {
> public:
>    using IFileStream::Mode;
> };
> ```

I have no opinion regarding that.  Whichever makes sense would be fine, so it's entirely up to you.  Let me know if you want me to add that as part of this PR.

**Comment by halx99** [comment]
> > Would be better?
> > ```c++
> > class FileStream : public IFileStream {
> > public:
> >    using IFileStream::Mode;
> > };
> > ```
> 
> I have no opinion regarding that. Whichever makes sense would be fine, so it's entirely up to you. Let me know if you want me to add that as part of this PR.

Yes, please add that as part of this PR, thanks

**Comment by rh101** [comment]
> Yes, please add that as part of this PR, thanks

Would it be:

`using IFileStream::Mode;`

or

`using enum IFileStream::Mode;`

I'm not 100% sure what the difference is.

**Comment by halx99** [comment]
> > Yes, please add that as part of this PR, thanks
> 
> Would it be:
> 
> `using IFileStream::Mode;`
> 
> or
> 
> `using enum IFileStream::Mode;`
> 
> I'm not 100% sure what the difference is.

`using IFileStream::Mode;` looks good, c++ compiler should auto detect it

**Comment by rh101** [comment]
> `using IFileStream::Mode;` looks good, c++ compiler should auto detect it

All done!

**Pull request merged**
