### PR TITLE
Improve build profiles

### LINKED ISSUE #2219: feature-request: Android 15 for 16 KB page sizes support
Android 15 has been released!
It may become the minimum adaptation requirement for listing on Google Play in the near future.
Notice that in the update information, there is a support requirement for [16 KB page sizes](https://developer.android.com/about/versions/15/behavior-changes-all#16-kb).
Will the engine be adapted in the future?
[Guides](https://developer.android.google.cn/guide/practices/page-sizes)

### PR DESCRIPTION
**Pull request by halx99**
1. Add `1k/build.profiles` for android ndk, sdk tools, emsdk ...
2. Android targetSdk and minSdk also control by 1k/build.profiles
3. You can override some build profiles in `.axproj` file, i.e android ndk, android target_sdk and min_sdk and others

### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [ ] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

**Comment by rh101** [comment]
@halx99 With this change, it's causing a slight issue with libraries that contain their own gradle scripts etc.  So, for example, in one library exists this section in `app/build.gradle`:

```
android {
    compileSdk PROP_COMPILE_SDK_VERSION.toInteger()
    namespace "com.library.some"

    defaultConfig {
        minSdkVersion PROP_MIN_SDK_VERSION
        targetSdkVersion PROP_TARGET_SDK_VERSION
        consumerProguardFiles 'proguard-rules.pro'
    }
}
```

`PROP_COMPILE_SDK_VERSION`, `PROP_MIN_SDK_VERSION` and `PROP_TARGET_SDK_VERSION` no longer exist in the top level project, since those have been moved to `.axmol`.  I realise it can be fixed by just keeping those values in `gradle.properties`, but now it means there would be multiple locations with those defines, being `.axmol` and `gradle.properties`, and there is a chance they can go out of sync.

Is there any other way to resolve this?

**Comment by rh101** [comment]
Also, how do we specify the settings in `.axmol`, such as which NDK version to use? Is it like this:

```
minSdk=26
targetSdk=34
ndkVer=26.3.11579264+
cmakeVer=3.28.1+
```

With the above, I'm getting this error:

`Caused by: java.lang.Exception: No installed ndk found, required 23.3.*`

**Comment by halx99** [comment]
> Also, how do we specify the settings in `.axmol`, such as which NDK version to use? Is it like this:
> 
> ```
> minSdk=26
> targetSdk=34
> ndkVer=26.3.11579264+
> cmakeVer=3.28.1+
> ```
> 
> With the above, I'm getting this error:
> 
> `Caused by: java.lang.Exception: No installed ndk found, required 23.3.*`

in .axproj should be: `ndk=r26d+`

**Comment by halx99** [comment]
Please refer to: https://github.com/axmolengine/axmol/blob/dev/1k/build.profiles

**Comment by rh101** [comment]
> in .axproj should be: ndkVer=r26d

No luck. Same error:
`Caused by: java.lang.Exception: No installed ndk found, required 23.3.*`

The NDKs are all in the `android-sdk\ndk` folder, and it has the following at the moment:
image

Just FYI, this was all working prior to the changes in this PR.  Is there anything else that needs to be changed?

**Comment by halx99** [comment]
Create `.axproj` in your exsits axmol project, and add `ndk=r26d+` in it

**Comment by halx99** [comment]
A migrate guide should be write in axmol wiki before axmol 2.3.0 release

**Comment by rh101** [comment]
> Create `.axproj` in your exsits axmol project, and add `ndk=r26d+` in it

It's already in there, and I just tested these settings:
```
minSdk=26
targetSdk=34
ndkVer=r26d+
```

Same error, `Caused by: java.lang.Exception: No installed ndk found, required 23.3.*`

I'll try this out on a new project to make sure it's not something in my existing project causing the problem.

**Comment by halx99** [comment]
please notice the key is `ndk` not `ndkVer` all keys should same with `1k/build.profiles`

**Comment by rh101** [comment]
A fresh project with the default settings in `.axproj` also caused the same error:
`Caused by: java.lang.Exception: No installed ndk found, required 23.3.*`

Is there something that needs to be set, like an environment variable?

**Comment by rh101** [comment]
> please notice the key is `ndk` not `ndkVer` all keys should same with `1k/build.profiles`

Oh! Sorry I totally missed that, since I noticed the `ndkVersion = buildProfiles['ndkVer']` line in `build.gradle`, and thought that was it. I'll test that out now, but I'm curious as to why a fresh project with no modifications would be having the same error.

**Comment by halx99** [comment]
I know what happen, if you don't set ndk version in `.axproj` to override `1k/build.profiles`, it will `r23d` which is not official released by google, but available on Android CI, you can use `./setup.ps1 -p android` to install it.

**Comment by rh101** [comment]
> I know what happen, if you don't set ndk version in `.axproj` to override `1k/build.profiles`, it will `r23d` which is not official released by google, but available on Android CI, you can use `./setup.ps1 -p android` to install it.

Makes perfect sense. I can see this being an issue though going forward for new projects, so can we have one set in the template to something that is officially realised by google?

**Comment by halx99** [comment]
The command line: `axmol -p android -c` also will auto setup ndk configured in `1k/build.profiles`

If rollback to official released ndk r23c, then the android 15 16KB page size support will not work

**Comment by rh101** [comment]
I'm getting this error now:
```
[CXX1110] Platform version 17 is unsupported by this NDK. Please change minSdk to at least 21 to avoid undefined behavior. To suppress this error, add android.ndk.suppressMinSdkVersionError=21 to the project's gradle.properties or set android.experimentalProperties["android.ndk.suppressMinSdkVersionError"]=21 in the Gradle build file.
```

Yet `.axmol` has the following:
```
minSdk=26
targetSdk=34
ndk=r26d+
```

**Comment by halx99** [comment]
I don't think upgrade ndk to r27(https://developer.android.com/about/versions/15/behavior-changes-all#16-kb) at axmol 2.x is good

**Comment by halx99** [comment]
> I'm getting this error now:
> 
> ```
> [CXX1110] Platform version 17 is unsupported by this NDK. Please change minSdk to at least 21 to avoid undefined behavior. To suppress this error, add android.ndk.suppressMinSdkVersionError=21 to the project's gradle.properties or set android.experimentalProperties["android.ndk.suppressMinSdkVersionError"]=21 in the Gradle build file.
> ```
> 
> Yet `.axmol` has the following:
> 
> ```
> minSdk=26
> targetSdk=34
> ndk=r26d+
> ```

Yes you should refer google ndk release page to check the minimal sdk support, and override build.profiles min_sdk in .axproj

**Comment by halx99** [comment]
> > I'm getting this error now:
> > ```
> > [CXX1110] Platform version 17 is unsupported by this NDK. Please change minSdk to at least 21 to avoid undefined behavior. To suppress this error, add android.ndk.suppressMinSdkVersionError=21 to the project's gradle.properties or set android.experimentalProperties["android.ndk.suppressMinSdkVersionError"]=21 in the Gradle build file.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Yet `.axmol` has the following:
> > ```
> > minSdk=26
> > targetSdk=34
> > ndk=r26d+
> > ```
> 
> Yes you should refer google ndk release page to check the minimal sdk support, and override build.profiles min_sdk in .axproj

do you totally read engine 1k/build.profiles

**Comment by rh101** [comment]
> I don't think upgrade ndk to r27(https://developer.android.com/about/versions/15/behavior-changes-all#16-kb) at axmol 2.x is good

Strange, because prior to the changes in this PR, the project was working perfectly fine with the following:
`def nbtInfo = axutils.findNativeBuildTools(project, "3.28.1+", "26.3.11579264+")`

**Comment by halx99** [comment]
should be 
```txt
min_sdk=21
target_sdk=34
ndk=r26d+
```

**Comment by rh101** [comment]
> do you totally read engine 1k/build.profiles

I thought I did, but just went through it again, and noticed the comment `# Android 15 16KB page size only supported by ndk r23 r25 from ci.android.com or r27+`

> should be
> 
> ```
> min_sdk=21
> target_sdk=34
> ndk=r26d+
> ```

Ok, I'll test that out.

**Comment by halx99** [comment]
After this PR, all build tools version are controlled by `1k/build.profles` and `.axproj`

**Comment by rh101** [comment]
> After this PR, all build tools version are controlled by `1k/build.profles` and `.axproj`

Sorry, I now understand what is going on.  What confused me were the changes in `build.gradle`, such as:
```
    def buildProfiles = AxmolUtils.resolveBuildProfiles(project)
    def packageName = buildProfiles['packageName']
    def cmakeVer = buildProfiles['cmakeVer']
    def cmakeOptions = Eval.me(buildProfiles['cmakeOptions'])
    def minSdk = buildProfiles['minSdk']
    def targetSdk = buildProfiles['targetSdk']
...
    ndkVersion = buildProfiles['ndkVer']
```

Now I get that these buildProfiles keys aren't the ones that should be used in the `.axmol` file.  So all the above values in `buildProfiles` are set in `axutils.gradle`, and the actual settings that can be configured are the ones listed in `1k/build.profles`.

Everything is now working when using the following:
```
min_sdk=26
target_sdk=35
ndk=r26d+
```

**Comment by rh101** [comment]
For the other issue related to libraries with their `build.gradle` files referencing the `PROP_COMPILE_SDK_VERSION`, `PROP_MIN_SDK_VERSION` and `PROP_TARGET_SDK_VERSION`, this seems to work:

```
apply from: project(':libaxmol').projectDir.toString() + "/axutils.gradle"

android {
    def buildProfiles = AxmolUtils.resolveBuildProfiles(project(':MyGame')) // requires reference to game project
    def packageName = "com.library.some"
    def minSdk = buildProfiles['minSdk']
    def targetSdk = buildProfiles['targetSdk']

    // Apply build profiles
    namespace packageName
    compileSdk targetSdk.toInteger()

    defaultConfig {
        minSdkVersion minSdk
        targetSdkVersion targetSdk
        consumerProguardFiles 'proguard-rules.pro'
    }
}
```

Would you know of any other way to get the main project so it can locate the `.axmol`, instead of using `AxmolUtils.resolveBuildProfiles(project(':MyGame'))`? If not, that's fine, just a minor inconvenience of having to update all libraries to have a reference to the game project.

EDIT:
Never mind! The following works, so no need to hard-code the project name:
`def buildProfiles = AxmolUtils.resolveBuildProfiles(project(":${rootProject.name}"))`

**Comment by halx99** [comment]
If not native project, you can call `AxmolUtils.resolveBasicBuildProfiles`

**Comment by AlexandreK38** [comment]
Hi! 
I just updated to latest version and discovered this change and that in `axutils.java` you use several times `System.env.AX_ROOT`
The issue is that I don't use a shared Axmol and don't set AX_ROOT at all, what can we do in this case?
We can toggle to use embedded axmol in the CMakeList.txt but here in java we can't s there is no way to link the `1k/build.profiles` using the new way.
For now I made it work by modifying this file to use project path and relative links instead of the `AX_ROOT` env, but it's not really great

**Comment by rh101** [comment]
@halx99 @AlexandreK38 What do you think about the changes in #2361 to fix the Android build issue for embedding Axmol in the game project?

**Comment by AlexandreK38** [comment]
All good for me 👍

**Pull request merged**
