### PR TITLE
Update README.md (add external Axmol forums)

### PR DESCRIPTION
**Pull request by aismann**
Which branch your pull-request should merge into?

- `dev`: Current 2.x BugFixs or Features

## Checklist before requesting a review
-  [ ] I have performed a self-review of my code.
-  [ ] If it is a core feature, I have added thorough tests.
-  [ ] I have checked readme and add important infos to this PR (if it needed).
-  [ ] I have added/adapted some tests too.

### CODE REVIEW

**Comment by paulocoutinhox** [comment]
Have the reddit too if you want add: https://www.reddit.com/r/axmol/

**Comment by halx99** [comment]
we already have discord in readme badge list

**Comment by aismann** [comment]
Ok I have not seen it. Close this PR

**Comment by aismann** [comment]
.

**Pull request closed without merging**
