### PR TITLE
[DRAFT DO NOT MERGE] Check BUILD_SHARED_LIBS ON for win32

### PR DESCRIPTION
**Pull request by crazyhappygame**
THIS PROJECT IS IN DEVELOPMENT MODE. Any pull requests should merge to branch `dev`, otherwise will be rejected immediately.

## Checklist before requesting a review
-  [ ] I have performed a self-review of my code.
-  [ ] If it is a core feature, I have added thorough tests.
-  [ ] I have checked readme and add important infos to this PR (if it needed).
-  [ ] I have added/adapted some tests too.

### CODE REVIEW

**Comment by halx99** [comment]
Will fixed by https://github.com/axmolengine/axmol/commit/640dda61ec89ef56fb12abb03948ae0ffbdfd598

**Comment by crazyhappygame** [comment]
@halx99 Thank you. You are super fast!

Please check https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html?highlight=target_file_dir#genex:TARGET_RUNTIME_DLLS

It looks like coping dependent DLL could be done with 1 line

**Comment by crazyhappygame** [comment]
BTW could you remove as well STATIC and SHARED from all add_library calls? In that way we can control all libraries with BUILD_SHARED_LIBS option

**Comment by halx99** [comment]
Some thirdparty libs doesn't support dll, so we can't do that

**Comment by halx99** [comment]
> @halx99 Thank you. You are super fast!
> 
> Please check https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html?highlight=target_file_dir#genex:TARGET_RUNTIME_DLLS
> 
> It looks like coping dependent DLL could be done with 1 line

done https://github.com/axmolengine/axmol/commit/e9c1726c31b2b2c394510b3019d36abd41552787

**Comment by crazyhappygame** [comment]
@halx99 Thank you!

**Pull request closed without merging**
