### PR TITLE
Ability to disable default implementations of HTTP and WebSocket clients

### PR DESCRIPTION
**Pull request by rh101**
Which branch your pull-request should merge into?

- `2.1`: BugFixes and Improvements for Current LTS branch

## Describe your changes
Allow the HttpClient and WebSocket implementations to be excluded from the build.  This may be because they are either not required, or the game project has its own implementations, so this would prevent build time conflicts in code.

Allow LLHTTP to be disabled if not required to avoid build time conflicts with game-side libraries.

## Issue ticket number and link
This may help with #1642

### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [x] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

**Comment by rh101** [comment]
Just an additional note.  As a work-around for the issue raised in #612, I'm currently using the changes in this PR to allow an alternative http library to be used in the a game project, otherwise there are too many compilation errors due to type conflicts.

**Comment by halx99** [comment]
Suggestion:
1. add option description to `CMakeOptions.md`
2. rename `AX_USE_XXX` to `AX_ENABLE_XXX` for core features

**Comment by rh101** [comment]
> Suggestion:
> 
>     1. add option description to `CMakeOptions.md`
> 
>     2. rename `AX_USE_XXX` to `AX_ENABLE_XXX` for core features

Will do.

**Comment by rh101** [comment]
Should `AX_WITH_LLHTTP` be changed as well, or leave it as is?

**Comment by halx99** [comment]
> Should `AX_WITH_LLHTTP` be changed as well, or leave it as is?

3rdparty just leave as-is

**Pull request merged**
