### PR TITLE
Enable default aidl file to project especially for In-app purchases

### PR DESCRIPTION
**Pull request by armanhossiny**
Which branch your pull-request should merge into?

- `dev`: Current 2.x BugFixs or Features
- `1.x`: 1.x BugFixs

### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [ ] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

**Review by halx99 — APPROVED** [review]

**Comment by rh101** [comment]
Isn't this functionality deprecated in Android?

**Comment by halx99** [comment]
Not sure, there is a stackoverflow thread: https://stackoverflow.com/questions/76232982/how-to-suppress-warning-it-will-be-removed-in-version-9-0-of-the-android-gradle

**Comment by rh101** [comment]
image

From here: https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes

This is really a project-specific option, and I personally feel that it is not a good idea to add it to the template.  If a developer requires it, then that developer can add it, but it's not something that should be forced on all developers creating new projects.

**Comment by halx99** [comment]
WARNING: The option setting 'android.defaults.buildfeatures.buildconfig=true' is deprecated.

Got this warning message: https://github.com/simdsoft/axmol/actions/runs/7584089520/job/20657048877

**Comment by halx99** [comment]
The docs may means the props in gradle.properties is deprecated, instead define per build.gradle DSL namespace like:
```txt
android {
   buildFeatures {
       buildconfog = true
   }
}
```

**Comment by rh101** [comment]
> The docs may means the props in gradle.properties is deprecated, instead define per build.gradle DSL namespace like:

I didn't realise it's still supported via build.gradle. All good!

**Pull request merged**
