### PR TITLE
Update README.md (Merge was overwritten: Add the upstream version of pugixml #1475

### PR DESCRIPTION
**Pull request by aismann**
Merge of #1475 was overwritten anyhow.
Add the upstream version of pugixml #1475

Which branch your pull-request should merge into?

- `dev`: Current 2.x BugFixs or Features

## Checklist before requesting a review
-  [x] I have performed a self-review of my code.
-  [ ] If it is a core feature, I have added thorough tests.
-  [] I have checked readme and add important infos to this PR (if it needed).
-  [ ] I have added/adapted some tests too.

### CODE REVIEW

**Comment by rh101** [comment]
> Merge of #1475 was overwritten anyhow.

How did that happen, and are we sure it hasn't happened to other PRs?

**Comment by aismann** [comment]
I dont check it. Only see it

Maybe this is the reason:
image

**Comment by halx99** [comment]
README.md.in

**Comment by rh101** [comment]
> README.md.in

Oh, so it wasn't an issue with the PR, it was just the wrong file that was edited. The changes need to be made to `README.md.in`.

Note that if the `README.md` isn't generated from `README.md.in`, then you would need to edit both files.

**Comment by aismann** [comment]
> > README.md.in
> 
> Oh, so it wasn't an issue with the PR, it was just the wrong file that was edited. The changes need to be made to `README.md.in`.

@halx99 
The changes need to be made always to `README.md.in` and  `README.md`?

**Comment by halx99** [comment]
> > > README.md.in
> > 
> > 
> > Oh, so it wasn't an issue with the PR, it was just the wrong file that was edited. The changes need to be made to `README.md.in`.
> 
> @halx99 The changes need to be made always to `README.md.in` and `README.md`?

Yes, otherwise will overwrite by github action `update-prebuilts'

**Pull request merged**
