### PR TITLE
Change extension folder structure to reduce file name conflicts

### LINKED ISSUE #1645: Axmol extension's includes conflict with project's includes
Axmol's `core/CMakeLists.txt` has this:

```
target_include_directories(${_AX_CORE_LIB}
    ...
    PUBLIC ${_AX_ROOT}/extensions
    ...
    INTERFACE ${_AX_ROOT}/extensions
```

This exposes all files in extensions folders to the project even if those extensions are disabled. The problem with this setup is that it can conflict with the custom libraries inside the project or with the project itself.

For example, we have a custom separate ImGui and Spine libraries integrated into our projects, and including `spine/SkeletonAnimation.h` leads to problems. Since `${_AX_ROOT}/extensions` is added to the include paths, the project ends up including `${_AX_ROOT}/extensions/spine/SkeletonAnimation.h` header and not ours.

I think `${_AX_ROOT}/extensions` should be removed from include paths, and each extension should add its own include paths, and only if the extension is enabled. Headers like `${_AX_ROOT}/extensions/spine/SkeletonAnimation.h` should be moved to something like `${_AX_ROOT}/extensions/spine/includes/spine/SkeletonAnimation.h`, and `${_AX_ROOT}/extensions/spine/includes` path should be added to the project only if Spine extension is turned on.

Note that this applies to all extensions, not just Spine.

### PR DESCRIPTION
**Pull request by rh101**
Which branch your pull-request should merge into?

- `2.1`: BugFixes and Improvements for Current LTS branch

## Describe your changes
Moved each extension into its own "src" folder.
Each extension `CMakeList.txt` now sets up the include paths for that extension.
LUA bindings generator updated, but this needs to be checked.
Fix issue with detecting Effekseer and DrawNodeEx extensions in cpp-tests.

Note that I manually updated the auto-generated lua bindings, so I haven't yet tested the changes to the LUA binding generator to see if it does generate the correct output. Hopefully that is the case, but if not, then any help with that specific part would be appreciated.

It seems that a few existing issues surfaced when the extension folder structure was changed, such as header files to inactive extensions being included when they shouldn't be.

FYI, the changes in this PR shouldn't break any existing code.  If anything, it would be a few include statements that would need to be fixed up in a project, assuming it uses extensions.

## Issue ticket number and link
#1645 

### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [x] I have performed a self-review of my code.
       
   Optional:
   - [x] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

**Comment by rh101** [comment]
There are issues with the LUA bindings generator, so attempting to fix that in order to complete this PR.

**Comment by rh101** [comment]
The LUA binding generator should be working now. If there are any concerns or suggestions, then I'll get around to having a look at them in 2 days time.

**Comment by halx99** [comment]
lgtm

**Comment by rh101** [comment]
Hold off on any merging. One last thing to do, which is fixing the pre-built paths in `AXLinkHelpers.cmake`.

EDIT: All done. Commit [d894c54](https://github.com/axmolengine/axmol/pull/1647/commits/d894c545c09a8f4ea633a1fe5c8540159b0026a2) should also fix the issue with yasio that has been reported on the Discord server (missing header search path and linker error with pre-builts).

**Review by halx99 — APPROVED** [review]

**Comment by halx99** [comment]
@rh101 the bot try override luabindings: https://github.com/axmolengine/axmol/pull/1648

**Pull request merged**
