### PR TITLE
Implement basic support for Game Center and Google Play Games Services

### PR DESCRIPTION
**Pull request by maksg**
Which branch your pull-request should merge into?

- `dev`: Current 2.x BugFixs or Features

I have created support for basic functionality of Game Center on Apple platforms and Google Play Games Services on Android.

Unfortunately I have no idea how to make it optional on Android. Maybe it could be added as parameter when creating project.
Also it requires minimum Android SDK 19. I could encapsulate the code in `if` but maybe we could just increase minimum version since Android versions below 4.4 are very old anyway.

### CODE REVIEW

**Comment by rh101** [comment]
@maksg This PR is forcing project-specific code into all applications that may not be using it, and there is no apparent way to disable all of it. This should be done in a separate extension or library that you add to your project, and not something that is embedded in the game engine. 

Judging by the code, there is absolutely no reason it should be added to the game engine.  I realize you made changes to `AxmolEngine.java`, but those changes do not belong there either.

**Comment by maksg** [comment]
@rh101 That's why I think it could be made optional by adding parameter to a creation command.
For example `axmol new -p org.axmol.hellocpp -d D:\dev\projects\ -l cpp --portrait HelloCpp --game-center`.

But it sure could be added as something separate. If you have any instructions on how to create extension for Axmol then I could try to move that to it.

**Comment by rh101** [comment]
> @rh101 That's why I think it could be made optional by adding parameter to a creation command. For example `axmol new -p org.axmol.hellocpp -d D:\dev\projects\ -l cpp --portrait HelloCpp --game-center`.
> 

That command is to create new projects, and adding switches that are unrelated to that task serves to overcomplicate and confuse things.

> But it sure could be added as something separate. If you have any instructions on how to create extension for Axmol then I could try to move that to it.

Sorry, just to clarify, I did not mean that this should be added to the Axmol extensions folder. It really does not belong in there either, or any part of the engine source tree.  

This should be its own project, as a separate module (folder) that a developer can just add to their game project, then hook it all up by adding a reference to it via CMakeLists.txt and a few lines of code.  

If you're not sure how to do that, there are plenty of sources online on how to achieve this, but I can create a simple project based on your source code if that would help you.

**Comment by maksg** [comment]
All right, I'll try to look it up myself how to do that. Unless this simple project is something really quick for you to do then I would appreciate that.

Thanks.

**Comment by rh101** [comment]
> All right, I'll try to look it up myself how to do that. Unless this simple project is something really quick for you to do then I would appreciate that.
> 
> Thanks.

Check this old addon for Cocos2d-x (which actually has GameCenter support too): https://github.com/newnon/avalon

Just use it as a reference for how to set it all up.  The CMakeLists.txt in that avalon project is, in my opinion, a mess, and perhaps not the best example to follow, but it does work.  

Other than that, I should be able to create a clearer example than that project in the next day or so.

**Comment by rh101** [comment]
@maksg Attached is the addon using your source code:

[thirdparty.zip](https://github.com/axmolengine/axmol/files/13432068/thirdparty.zip)

Although I haven't run it, I did do a build for Windows and Android to make sure it works.

Extract that archive into your game project folder, so it will be something like:
`[gameproject]/thirdparty/maksg/`

The following steps are how to integrate it with a game project.

In the project root `CMakeLists.txt`, link it like this:

```
# maksg extension
set(MAKSG_GAMECENTER ON CACHE BOOL "" FORCE)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/maksg ${PROJECT_BINARY_DIR}/maksg)
get_target_property(maksg_INCLUDE_DIRS maksg_ext INTERFACE_INCLUDE_DIRECTORIES)
target_link_libraries(${APP_NAME} maksg_ext)
target_include_directories(${APP_NAME}
    PRIVATE ${maksg_INCLUDE_DIRS}
)
```

For Android, it needs to be added as a dependency.  

Add the following lines to `proj.android/settings.gradle`:

```
include ':maksg_gamecenter'
project(':maksg_gamecenter').projectDir = new File(settingsDir, '../thirdparty/maksg/proj.android/Google/GameCenter')
```

Add `implementation project(path: ':maksg_gamecenter')` to the dependencies section in `proj.android/app/build.gradle`, for example:

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':libaxmol')

    implementation project(path: ':maksg_gamecenter')
}
```

Now to initialize it, call the `GameCenter.init()` method in `onCreate` of `proj.android/app/src/org/axmol/cpp/AppActivity.java`:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ...
        ...
        // DO OTHER INITIALIZATION BELOW
        GameCenter.init();
    }
```

That's pretty much it.  Similar code would be used for the other platforms, and all of this requires no changes to the Axmol engine source.

I hope it all makes sense.

**Comment by rh101** [comment]
Just to re-iterate why I strongly believe that functionality like this does not belong in the game engine source:

1 - Adding support for 3rd party services isn't a core engine function
2 - The implementation may be limited or unsuitable, and likely to require constant maintenance due to changes in the 3rd party service API.
3 - This is better served by a having it as a separate library or module that can be added by the developer if it is required (as shown in the prior posts within this thread)

@halx99 If you agree with this, then please do not merge this in.  This PR should be closed, and quite frankly, functionality like this should never be considered for inclusion as part of the game engine source code.

**Comment by aismann** [comment]
Maybe add it to the Interesting related #694 as alternative (if no merge)

**Comment by maksg** [comment]
@rh101 I agree with your points, I just didn't have enough knowledge to come up with something better at the moment so I decided to bring it here with hope that some changes could be made by someone with better skills.

Thanks to your code I may be able to do that. I'll polish everything up and open source it. Once I'm done I'll give you update with links alongside another repo with in-app purchases support which is also almost done. Hopefully this will help devs who also wanted to migrate from sdkbox.

**Comment by rh101** [comment]
> Thanks to your code I may be able to do that. I'll polish everything up and open source it. Once I'm done I'll give you update with links alongside another repo with in-app purchases support which is also almost done. Hopefully this will help devs who also wanted to migrate from sdkbox.

No problem at all.  

Please do close this PR when you can, as it serves no purpose being open.  Once you do finish your project, and assuming it's uploaded to a repo somewhere, please do update post #694 as aismann mentioned earlier.

**Pull request closed without merging**
