### PR TITLE
Enable running `unit-tests` in GitHub workflow

### PR DESCRIPTION
**Pull request by smilediver**
Trying to enable running `unit-tests` in GitHub workflow.

### CODE REVIEW

**Comment by smilediver** [comment]
Windows is hitting #1872 issue.

@halx99 Can you help me in setting up running on macOS? I can't figure out how to insert arch for the command line here: https://github.com/smilediver/axmol/blob/ade1eba39c25f3d1a3909019db4fb9cdaf3067ba/.github/workflows/build.yml#L124

And I also have no idea why Linux fails. I don't know if the path to exe is wrong or something else...

**Comment by halx99** [comment]
sure

**Comment by halx99** [comment]
The linux will crash due to initialize FileUtilsLinux too early before entering `main` entrypoint

**Comment by halx99** [comment]
does the doctest support run tests in `main` function?

**Comment by halx99** [comment]
image

**Comment by smilediver** [comment]
Thanks for getting this to work!

**Pull request merged**
