### PR TITLE
Mark AXLOG, AXLOGINFO, AXLOGWARN, AXLOGERROR deprecated

### PR DESCRIPTION
**Pull request by halx99**
## Describe your changes

Remove all old log macro calls from `core` folder, instead use c++20 format style macros: AXLOGD, AXLOGI, AXLOGW, AXLOGE.

### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [ ] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

**Comment by johnspeny** [comment]
I have mostly used AXLOG, so I should shift to ax::print I guess.

**Comment by halx99** [comment]
ax::print also deprecated, you can still use them until axmol 2.2.x

**Comment by johnspeny** [comment]
What do we use now?.

**Comment by paulocoutinhox** [comment]
@johnspeny you need use AXLOGD, AXLOGW, AXLOGE, etc.

**Comment by johnspeny** [comment]
Didn't know they existed, nice work.

**Comment by rh101** [comment]
@halx99 This change has resulted in a lot of log spam, such as the following:

```
16:34:49:968	I/[2024-07-05 16:34:49.737][TID:795c]x = 1643 y = 990
16:34:49:968	I/[2024-07-05 16:34:49.861][TID:795c]Ending touches with id: 0, x=1643, y=990
16:34:49:968	D/[2024-07-05 16:34:49.920][TID:795c]deallocing AnimationFrame: 0x274723b2980
16:34:49:968	D/[2024-07-05 16:34:49.920][TID:795c]deallocing AnimationFrame: 0x274723b38f0
16:34:49:968	D/[2024-07-05 16:34:49.920][TID:795c]deallocing AnimationFrame: 0x274723b2a50
16:34:49:968	D/[2024-07-05 16:34:49.921][TID:795c]deallocing AnimationFrame: 0x274723b2b20
16:34:49:968	D/[2024-07-05 16:34:49.921][TID:795c]deallocing AnimationFrame: 0x274723b5630
16:34:49:968	D/[2024-07-05 16:34:49.921][TID:795c]deallocing AnimationFrame: 0x274723b5700
16:34:49:968	D/[2024-07-05 16:34:49.922][TID:795c]deallocing AnimationFrame: 0x274723b42b0
16:34:49:968	D/[2024-07-05 16:34:49.923][TID:795c]deallocing AnimationFrame: 0x274723b6740
16:34:49:968	D/[2024-07-05 16:34:49.923][TID:795c]deallocing AnimationFrame: 0x274723b5970
16:34:49:968	D/[2024-07-05 16:34:49.923][TID:795c]deallocing AnimationFrame: 0x274723b0350
16:34:49:968	D/[2024-07-05 16:34:49.924][TID:795c]deallocing AnimationFrame: 0x274723af170
16:34:49:968	D/[2024-07-05 16:34:49.924][TID:795c]deallocing AnimationFrame: 0x274723b09d0
16:34:49:968	D/[2024-07-05 16:34:49.924][TID:795c]deallocing AnimationFrame: 0x274723af240
16:34:49:968	D/[2024-07-05 16:34:49.925][TID:795c]deallocing AnimationFrame: 0x274723b1050
16:34:49:968	D/[2024-07-05 16:34:49.925][TID:795c]deallocing AnimationFrame: 0x274723af310
16:34:49:968	D/[2024-07-05 16:34:49.925][TID:795c]deallocing AnimationFrame: 0x274723af3e0
16:34:49:968	D/[2024-07-05 16:34:49.925][TID:795c]deallocing AnimationFrame: 0x274723b1bb0
16:34:49:968	D/[2024-07-05 16:34:49.925][TID:795c]deallocing AnimationFrame: 0x274723b1460
16:34:49:968	D/[2024-07-05 16:34:49.926][TID:795c]deallocing AnimationFrame: 0x274723afcd0
16:34:49:968	D/[2024-07-05 16:34:49.945][TID:795c]deallocing AnimationFrame: 0x2746ee97720
16:34:49:968	D/[2024-07-05 16:34:49.945][TID:795c]deallocing AnimationFrame: 0x2746ee96540
16:34:49:968	D/[2024-07-05 16:34:49.945][TID:795c]deallocing AnimationFrame: 0x2746ee981b0
```

Can we please have these use AXLOGV instead of AXLOGD/AXLOGI?
```
AnimationFrame::~AnimationFrame()
{
    AXLOGD("deallocing AnimationFrame: {}", fmt::ptr(this));

    AX_SAFE_RELEASE(_spriteFrame);
}

AXLOGI("Ending touches with id: {}, x={}, y={}", (int)id, x, y);

AXLOGI("Moving touches with id: {}, x={}, y={}, force={}, maxFource={}", (int)id, x, y, force, maxForce);

AXLOGI("x = {} y = {}", touch->getLocationInView().x, touch->getLocationInView().y);
```

Is the `AnimationFrame::~AnimationFrame()` log call even useful at all?

**Comment by halx99** [comment]
Yes, should use `AXLOGV` instead

**Pull request merged**
