### PR TITLE
Add Anchored Sprite Class

### PR DESCRIPTION
**Pull request by DelinWorks**
THIS PROJECT IS IN DEVELOPMENT MODE. Any pull requests should merge to branch `dev`, otherwise will be rejected immediately.

## Describe your changes
added anchored sprite, gives a much better anchoring alternative compared to the traditional method of anchoring the node

Example Code:
```
// add "HelloWorld" splash screen"
AnchoredSprite* sprite = AnchoredSprite::create("HelloWorld.png"sv);
if (sprite == nullptr)
{
    problemLoading("'HelloWorld.png'");
}
else
{
    // position and anchor the sprite on the center of the screen, this is an override function
    sprite->setAnchorPoint({ 1,0.5 });

    sprite->setPosition(Vec2(visibleSize.width / 2 + origin.x, visibleSize.height / 2 + origin.y));
    sprite->addChild(label, 1);
    label->setPosition(0, 0);
    // add the sprite as a child to this layer
    this->addChild(sprite, 0);
    auto drawNode = DrawNode::create();
    drawNode->setPosition(Vec2(0, 0));
    addChild(drawNode);

    drawNode->drawRect(safeArea.origin, safeArea.origin + safeArea.size, Color4F::BLUE);
}
```
Example with Touch Listener:
```
auto* listener = EventListenerTouchOneByOne::create();
listener->onTouchBegan = [this](Touch* touch, Event* event) {
    auto target = static_cast<AnchoredSprite*>(event->getCurrentTarget());

    Vec2 locationInNode = target->convertToNodeSpace(touch->getLocation());
    Rect rect = target->getTouchRect();

    if (rect.containsPoint(locationInNode))
    {
        log("sprite began... x = %f, y = %f", locationInNode.x, locationInNode.y);

        return true;
    }
    return false;
    };

_eventDispatcher->addEventListenerWithSceneGraphPriority(listener, sprite);
```

I added the function `getTouchRect` which deals with content size and rect offsets to make touch listener work.
 
## Checklist before requesting a review
-  [x] I have performed a self-review of my code.
-  [x] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by aismann** [comment]
@DelinWorks 
Why not add your example code to cpp_tests?

**Comment by DelinWorks** [comment]
Don't worry! working on it

**Comment by aismann** [comment]
@halx99 ,
Will it be part of the native Axmol engine?
It's a very special feature, but maybe someone can use it.

**Comment by crazyhappygame** [comment]
@DelinWorks Could you explain how AnchoredSprite is different from Sprite and what problems we would like to solve with this class?

**Comment by DelinWorks** [comment]
@crazyhappygame If you try to add children to a sprite with an anchor different than 0.5 than it will be frustrating because the node system moves the entire node instead of its vertices, so this class anchors the vertices and doesn't do anything to the node class, refer to #998 to learn more or you can take a look at the sprite test and see what I mean.

**Comment by crazyhappygame** [comment]
OK. Thank you. So for AnchoredSprite child nodes (0,0) is anchor point of parent. 
With Sprite we can achieve the same by adjusting position ```child->setPosition(parent->getContentSize())```

**Comment by aismann** [comment]
@DelinWorks 
Maybe the title of the tester is not correct?
image
"Testing AnchoredSprite" is more self explaining

**Pull request merged**
