### PR TITLE
[Apple] Fix for missing resources

### PR DESCRIPTION
**Pull request by rh101**
## Describe your changes
~~It seems that iOS and MacOS require resources to be mapped to the "Resources" folder in the Xcode project, otherwise the content will not be found at runtime.~~

The actual issue is that the resources need to be marked as such in CMake so that they are set to the correct destination in the Xcode project (Build Phases->Copy Files, with "Destination" set to "Resources").

The specific CMake property that needs to be set correctly is `MACOSX_PACKAGE_LOCATION`. More details in the following posts below.

Tested cpp and lua project builds for iOS sim, iOS device, and Mac OS M1, and they're now working correctly.

## Issue ticket number and link
#1087 

## Checklist before requesting a review
-  [x] I have performed a self-review of my code.
-  [ ] If it is a core feature, I have added thorough tests.
-  [ ] I have checked readme and add important infos to this PR (if it needed).
-  [ ] I have added/adapted some tests too.

### CODE REVIEW

**Comment by halx99** [comment]
Does there has any apple docoment indicate the resouce folder name must be `Resources`?

**Comment by rh101** [comment]
> Does there has any apple docoment indicate the resouce folder name must be `Resources`?

https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW14
https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/20001119-110730
https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW19

and this regarding CMake:
https://cmake.org/cmake/help/latest/prop_tgt/RESOURCE.html

For Mac OS, this is the bundle structure:
image

For iOS, it's a flat structure:
image

The change made in PR #1072 to have them all in "Contents" is fine, but when mapping for Xcode, it seems to require them in a "Resources" folder within the project tree, and on build, it places them in the correct path for the app bundles.  It may be just an Xcode requirement to have them in a "Resources" folder within the project, but I honestly don't know.

**Comment by rh101** [comment]
In Xcode, the build phase copies everything into "Resources" for Mac OS apps, so maybe there is something missing from the cmake configuration that isn't properly setting this up:

image
image

Same for iOS project:

image

**Comment by rh101** [comment]
The only change in this PR is to affect these cmake helpers:

`ax_mark_multi_resources` and `ax_mark_resources`

From my understanding of how it works, it's not actually copying any files, it's just marking them as resources, but is there something that needs to be changed in here (from latest axmol code):
```
# mark `FILES` as resources, files will be put into sub-dir tree depend on its absolute path
function(ax_mark_resources)
    set(oneValueArgs BASEDIR RESOURCEBASE)
    set(multiValueArgs FILES)
    cmake_parse_arguments(opt "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT opt_RESOURCEBASE)
        set(opt_RESOURCEBASE Resources)
    endif()

    get_filename_component(BASEDIR_ABS ${opt_BASEDIR} ABSOLUTE)
    foreach(RES_FILE ${opt_FILES} ${opt_UNPARSED_ARGUMENTS})
        get_filename_component(RES_FILE_ABS ${RES_FILE} ABSOLUTE)
        file(RELATIVE_PATH RES ${BASEDIR_ABS} ${RES_FILE_ABS})
        get_filename_component(RES_LOC ${RES} PATH)
        set_source_files_properties(${RES_FILE} PROPERTIES
                                    MACOSX_PACKAGE_LOCATION "${opt_RESOURCEBASE}/${RES_LOC}"
                                    HEADER_FILE_ONLY 1
                                    )

        if(XCODE OR VS)
            string(REPLACE "/" "\\" ide_source_group "${opt_RESOURCEBASE}/${RES_LOC}")
            source_group("${ide_source_group}" FILES ${RES_FILE})
        endif()
    endforeach()
endfunction()
```

**Comment by rh101** [comment]
Just found the problem! 

If "Content" is passed to this:
`ax_mark_multi_resources(common_content_files RES_TO "Content" FOLDERS ${content_folder})`

Look at what happens here in the Xcode project:
image

Notice the issue? It's setting the `Destination` field to `Executables`, rather than `Resources`.
image

**Comment by rh101** [comment]
In `ax_mark_resources`, I just did a quick test by changing:

        set_source_files_properties(${RES_FILE} PROPERTIES
                                    MACOSX_PACKAGE_LOCATION "${opt_RESOURCEBASE}/${RES_LOC}"
                                    HEADER_FILE_ONLY 1
                                    )

to this

        set_source_files_properties(${RES_FILE} PROPERTIES
                                    MACOSX_PACKAGE_LOCATION "Resources/${RES_LOC}"
                                    HEADER_FILE_ONLY 1
                                    )

and even if I "Content" is passed to this in the game `CMakeLists.txt`:
`ax_mark_multi_resources(common_content_files RES_TO "Content" FOLDERS ${content_folder})`

The app worked on iOS.

**Comment by rh101** [comment]
As far as I can tell from all of the above, the changes in this PR are correct.  The other option would be to hardcode "Resources" in the cmake `ax_mark_resources`, changing this:

`MACOSX_PACKAGE_LOCATION "${opt_RESOURCEBASE}/${RES_LOC}"`

to this:
`MACOSX_PACKAGE_LOCATION "Resources/${RES_LOC}"`

Assuming that it is only ever used for resources, and the files **never** require a different "Destination" (`RESOURCEBASE`) to ever be set.

**Comment by rh101** [comment]
I now have a bit more of an understanding regarding how this all works.  The `MACOSX_PACKAGE_LOCATION` property for files that we want as resources do need to be prefixed with "Resources" in their path in order to work for Apple app bundles.

So, technically, setting the `MACOSX_PACKAGE_LOCATION` to this would be fine:
```
set_source_files_properties(${RES_FILE} PROPERTIES
                                    MACOSX_PACKAGE_LOCATION "Resources/${RES_LOC}"
                                    HEADER_FILE_ONLY 1
                                    )
```

The next issue is to do what the display within the IDE via `source_group`. This section is for both XCODE and VS:

        if(XCODE OR VS)
            string(REPLACE "/" "\\" ide_source_group "${opt_RESOURCEBASE}/${RES_LOC}")
            source_group("${ide_source_group}" FILES ${RES_FILE})
        endif()

If we set `MACOSX_PACKAGE_LOCATION "Resources/${RES_LOC}"`, then we can still pass in "Content" to this in the game `CMakeLists.txt`:
`ax_mark_multi_resources(common_content_files RES_TO "Content" FOLDERS ${content_folder})`

and in the IDE, it'll show up in the "Content" folder, rather than "Resources".

On the other hand, if we leave it as:
`MACOSX_PACKAGE_LOCATION "${opt_RESOURCEBASE}/${RES_LOC}"`

and pass in "Resources" in:
`ax_mark_multi_resources(common_content_files RES_TO "Resources" FOLDERS ${content_folder})`

Then both XCODE and VS IDEs will show them in a "Resources" folder within the project tree (that is what happens with the changes in this PR).  As you know, it's just a visual thing, and does not affect the actual folder structure or build.

**Comment by mariusz102102** [comment]
@rh101 thank you for instigation.

@rh101 @halx99 
Is it possible to create automated CI test to detect that engine is in healthy state?
Maybe run cpp-test in some special mode?

As far I remember windows gihub CI hosts allows to run GUI app. Linux not possible. Not sure about MacOS

**Pull request merged**
