### PR TITLE
[IMPROVMENT] Rename `RngSeed` to `FastRNG`.

### PR DESCRIPTION
**Pull request by DelinWorks**
Refer to #706

### CODE REVIEW

**Comment by rh101** [comment]
@DelinWorks Avoid committing unrelated changes at the same time, and the same goes for the PR.  In this PR there are changes to the `RENAMED_TYPES.md`, which has nothing to do with the random number generator.

There are many reasons for why this is important, so for future commits and PRs, please do try to avoid this.

**Comment by DelinWorks** [comment]
> @DelinWorks Avoid committing unrelated changes at the same time, and the same goes for the PR. In this PR there are changes to the `RENAMED_TYPES.md`, which has nothing to do with the random number generator.
> 
> There are many reasons for why this is important, so for future commits and PRs, please do try to avoid this.

It is related I don't know what you mean

**Comment by rh101** [comment]
> It is related I don't know what you mean

The changes made to the text in the RENAMED_TYPES.md file have nothing to do with the FastRNG changes.  

You can see two commits here:

image

Both of them, I assume, went into the same branch, which is actually what caused the issue.

For each specific issue, you should create a separate branch, commit to it, and then create the PR from that. In this case, they should have been to two different branches.  Once the PR is merged (or no longer required for that specific issue), then the branch can be deleted.

**Comment by DelinWorks** [comment]
Fair enough!

**Pull request merged**
