### PR TITLE
Allow certain code modules to be removed from build process

### PR DESCRIPTION
**Pull request by rh101**
## Describe your changes
This is an attempt at allowing a developer to turn off certain aspects of the game engine source so that they are not built, reducing build times and final binary file size.

The new options are:
```
option(AX_ENABLE_3D "Build 3D support" ON)
option(AX_ENABLE_PHYSICS3D "Build Physics3D support" ON)
option(AX_ENABLE_NAVMESH "Build NavMesh support" ON)
option(AX_ENABLE_MEDIA "Build media support" ON)
option(AX_ENABLE_AUDIO "Build audio support" ON)
```

### For each PR
- [x] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [x] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

**Comment by halx99** [comment]
Thanks, could add these new options to https://github.com/axmolengine/axmol/blob/dev/CMakeOptions.md?

**Comment by rh101** [comment]
> Thanks, could add these new options to https://github.com/axmolengine/axmol/blob/dev/CMakeOptions.md?

Will do!

**Comment by halx99** [comment]
@rh101 seems this PR cause crash, just enter first test of cpp-tests on linux

**Comment by halx99** [comment]
And recommend refactor this defines in `base/Config.h`, please help control per core feature by single feature macro, i.e.  rename `AX_USE_PHYSICS` to `AX_ENABLE_PHYSICS`.
```cpp
/** Use physics integration API. */
//  It works with:
// Chipmunk2D or Box2D
#ifndef AX_USE_PHYSICS
#    define AX_USE_PHYSICS 1
#endif
#if (AX_USE_PHYSICS)
/** Use Chipmunk2D physics 2d engine on physics integration API. */
#    ifndef AX_ENABLE_CHIPMUNK_INTEGRATION
#        define AX_ENABLE_CHIPMUNK_INTEGRATION 0
#    endif
/** or use Box2D physics 2d engine on physics integration API. */
#    ifndef AX_ENABLE_BOX2D_INTEGRATION
#        define AX_ENABLE_BOX2D_INTEGRATION 1
#    endif
#endif  // AX_USE_PHYSICS

/** Use 3d physics integration API. */
#ifndef AX_USE_3D_PHYSICS
#    if (AX_TARGET_PLATFORM == AX_PLATFORM_IOS || AX_TARGET_PLATFORM == AX_PLATFORM_MAC ||       \
         AX_TARGET_PLATFORM == AX_PLATFORM_WIN32 || AX_TARGET_PLATFORM == AX_PLATFORM_WINRT ||   \
         AX_TARGET_PLATFORM == AX_PLATFORM_ANDROID || AX_TARGET_PLATFORM == AX_PLATFORM_LINUX || \
         AX_TARGET_PLATFORM == AX_PLATFORM_WASM)
#        define AX_USE_3D_PHYSICS 0
#    endif
#endif

#if (AX_USE_3D_PHYSICS)
/** Use bullet physics engine. */
#    ifndef AX_ENABLE_BULLET_INTEGRATION
#        define AX_ENABLE_BULLET_INTEGRATION 1
#    endif
#endif

/** Use 3D navigation API */
#ifndef AX_USE_NAVMESH
#    define AX_USE_NAVMESH 0
#endif
```

**Comment by rh101** [comment]
> And recommend refactor this defines in `base/Config.h`, please help control per core feature by single feature macro, i.e. rename `AX_USE_PHYSICS` to `AX_ENABLE_PHYSICS`.

Will do! I'll make the changes right now.  

Regarding Linux, I don't have a test box to use, but can set one up in around 12 hours (from this post).

**Pull request merged**
