### PR TITLE
Resize on Windows

### PR DESCRIPTION
**Pull request by pietpukkel**
Fixed resize on Windows

THIS PROJECT IS IN DEVELOPMENT MODE. Any pull requests should merge to branch `dev`, otherwise will be rejected immediately.

## Describe your changes

Added setFrameSize in onGLFWWindowSizeCallback. This fixes the issue with the Windows not being properly resizeable.

## Issue ticket number and link
1025
https://github.com/axmolengine/axmol/issues/1025

## Checklist before requesting a review
-  [x] I have performed a self-review of my code.
-  [ ] If it is a core feature, I have added thorough tests.
-  [ ] I have checked readme and add important infos to this PR (if it needed).
-  [ ] I have added/adapted some tests too.

### CODE REVIEW

**Review by halx99 — CHANGES_REQUESTED** [review]
Thanks, but maybe follow code is better:
```cpp
void GLViewImpl::onGLFWWindowSizeCallback(GLFWwindow* /*window*/, int w, int h)
{
    if (w && h && _resolutionPolicy != ResolutionPolicy::UNKNOWN)
    {
        /*
         x-studio spec, fix view size incorrect when window size changed.
         The original code behavior:
         1. first time enter full screen: w,h=1920,1080
         2. second or later enter full screen: will trigger 2 times WindowSizeCallback
           1). w,h=976,679
           2). w,h=1024,768

         @remark:
         1. we should use glfwSetWindowMonitor to control the window size in full screen mode
         2. on size callback, we don't needs invoke platform windows size again, i.e. glfwSetWindowSize,
         so invoke super setFrameSize to sync screenSize immdiately
         @see also: updateWindowSize (call after enter/exit full screen mode)
        */
        GLView::setFrameSize(w, h);
        updateDesignResolutionSize();

        Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(GLViewImpl::EVENT_WINDOW_RESIZED, nullptr);
    }
}
```

And I create window with `resizable=true`, works perfect:
image

**Comment by pietpukkel** [comment]
Isn’t that the same code but with the SetFrameSize after the comment instead of before? In any case, if it works its fine with me :-)

On 11 Jan 2023, at 10:50, 一线灵|Deal ***@***.***> wrote:



@halx99 requested changes on this pull request.

Thanks, but maybe follow code is better:

void GLViewImpl::onGLFWWindowSizeCallback(GLFWwindow* /*window*/, int w, int h)
{
    if (w && h && _resolutionPolicy != ResolutionPolicy::UNKNOWN)
    {
        /*
         x-studio spec, fix view size incorrect when window size changed.
         The original code behavior:
         1. first time enter full screen: w,h=1920,1080
         2. second or later enter full screen: will trigger 2 times WindowSizeCallback
           1). w,h=976,679
           2). w,h=1024,768

         @remark:
         1. we should use glfwSetWindowMonitor to control the window size in full screen mode
         2. on size callback, we don't needs invoke platform windows size again, i.e. glfwSetWindowSize,
         so invoke super setFrameSize to sync screenSize immdiately
         @see also: updateWindowSize (call after enter/exit full screen mode)
        */
        GLView::setFrameSize(w, h);
        updateDesignResolutionSize();

        Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(GLViewImpl::EVENT_WINDOW_RESIZED, nullptr);
    }
}

And I create window with resizable=true, works perfect:
[image]<https://user-images.githubusercontent.com/6977319/211773736-008eb896-7748-4633-9c97-9bcb1b9d7012.png>

**Comment by halx99** [comment]
It's ok:
```cpp
void GLViewImpl::onGLFWWindowSizeCallback(GLFWwindow* /*window*/, int w, int h)
{
    if (w && h && _resolutionPolicy != ResolutionPolicy::UNKNOWN)
    {
         /* Invoke `GLView::setFrameSize` to sync screen immediately,
         ** this->setFrameSize will invoke `glfwSetWindowSize` which is unnecessary.
         */
         GLView::setFrameSize(w, h);

        /*
         x-studio spec, fix view size incorrect when window size changed.
         The original code behavior:
         1. first time enter full screen: w,h=1920,1080
         2. second or later enter full screen: will trigger 2 times WindowSizeCallback
           1). w,h=976,679
           2). w,h=1024,768

         @remark:
         1. we should use glfwSetWindowMonitor to control the window size in full screen mode
         @see also: updateWindowSize (call after enter/exit full screen mode)
        */
        updateDesignResolutionSize();

        Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(GLViewImpl::EVENT_WINDOW_RESIZED, nullptr);
    }
}
```

**Comment by pietpukkel** [comment]
Ah; I see the difference. Thanks (I am just a humble hobbyist ;-)). Learning every day.

On 11 Jan 2023, at 11:31, 一线灵|Deal ***@***.***> wrote:



It's ok:

void GLViewImpl::onGLFWWindowSizeCallback(GLFWwindow* /*window*/, int w, int h)
{
    if (w && h && _resolutionPolicy != ResolutionPolicy::UNKNOWN)
    {
         /* Invoke `GLView::setFrameSize` to sync screen immediately,
         ** this->setFrameSize will invoke `glfwSetWindowSize` which is unnecessary.
         */
         GLView::setFrameSize(w, h);

        /*
         x-studio spec, fix view size incorrect when window size changed.
         The original code behavior:
         1. first time enter full screen: w,h=1920,1080
         2. second or later enter full screen: will trigger 2 times WindowSizeCallback
           1). w,h=976,679
           2). w,h=1024,768

         @remark:
         1. we should use glfwSetWindowMonitor to control the window size in full screen mode
         @see also: updateWindowSize (call after enter/exit full screen mode)
        */
        updateDesignResolutionSize();

        Director::getInstance()->getEventDispatcher()->dispatchCustomEvent(GLViewImpl::EVENT_WINDOW_RESIZED, nullptr);
    }
}

**Pull request merged**
