### PR TITLE
Allow to override AX_USE_COMPAT_GL from user's CMakeLists.txt

### PR DESCRIPTION
**Pull request by smilediver**
Which branch your pull-request should merge into?

- `dev`: Current 2.x BugFixs or Features

## Describe your changes

This change enables users to override `AX_USE_COMPAT_GL` option from user's `CMakeLists.txt`. We need to be able to force the use of OpenGL on macOS, because we have shader graph editor, that generates and previews shaders in runtime.

Current fix is probably not optimal, so I'm willing to change it if you can suggest a better way to implement it.

## Issue ticket number and link

N/A

### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [ ] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

**Comment by halx99** [comment]
the original code is optional variable, so you can set it to TRUE as a cache variable at your cmake file

**Comment by smilediver** [comment]
I've tried overriding the value in project's CMakeLists.txt file with: `set(AX_USE_COMPAT_GL ON)` and `set(AX_USE_COMPAT_GL ON CACHE BOOL "enable AX_USE_COMPAT_GL" FORCE)`, but `cmake_dependent_option()` call always overrides the value (I've printed it before and after the call).

P.S. I'm testing on macOS.

**Comment by rh101** [comment]
> I've tried overriding the value in project's CMakeLists.txt file with: `set(AX_USE_COMPAT_GL ON)` and `set(AX_USE_COMPAT_GL ON CACHE BOOL "enable AX_USE_COMPAT_GL" FORCE)`, but `cmake_dependent_option()` call always overrides the value (I've printed it before and after the call).

`cmake_dependent_option` won't allow the option to be set by the user unless all the items in the dependency list are true, which in this case is the requirement to have "WIN32" set.  No matter what you do, it won't work in it's current form.

Perhaps change that entire block to something like this may work:
```
if(WIN32)
    option(AX_USE_COMPAT_GL "Whether use compatibility GL as render backend" ON)
elseif(MACOSX)
    option(AX_USE_COMPAT_GL "Whether use compatibility GL as render backend" OFF)
else()
    set(AX_USE_COMPAT_GL OFF CACHE BOOL "Whether use compatibility GL as render backend" FORCE)
endif()
```

**Comment by smilediver** [comment]
Yeah, it's probably a better solution. If everyone agrees, I can change it to that.

**Comment by halx99** [comment]
does double OFF works?

**Comment by rh101** [comment]
> does double OFF works?

Sorry, I'm not sure what you mean.

**Comment by halx99** [comment]
> > does double OFF works?
> 
> Sorry, I'm not sure what you mean.

discard me

**Comment by halx99** [comment]
I have test on windows, it's works from command line `cmake -B buildtest -DAX_USE_COMPAT_GL=ON` and cmake:
```cmake
cmake_dependent_option(AX_USE_COMPAT_GL "Whether use compatibility GL as render backend" ON "MACOS" OFF)
```

**Comment by rh101** [comment]
> I have test on windows, it's works from command line `cmake -B buildtest -DAX_USE_COMPAT_GL=ON` and cmake:
> 
> ```cmake
> cmake_dependent_option(AX_USE_COMPAT_GL "Whether use compatibility GL as render backend" ON "MACOS" OFF)
> ```

Shouldn't it be "OFF" by default for MACOSX?

`cmake_dependent_option(AX_USE_COMPAT_GL "Whether use compatibility GL as render backend" OFF "MACOS" OFF)`

Also, do you mean add both lines in `core/CMakeLists.txt`, one for WIN32 and another for MACOSX?

```
cmake_dependent_option(AX_USE_COMPAT_GL "Whether use compatibility GL as render backend" ON "WIN32" OFF)
cmake_dependent_option(AX_USE_COMPAT_GL "Whether use compatibility GL as render backend" OFF "MACOS" OFF)`
```
Or did you mean something else?

**Comment by halx99** [comment]
sorry my mistake: the value in CMakeCache.txt is correct, and type is `:INTERNAL`, but in cmake config step incorrect

**Comment by halx99** [comment]
> WIN32

maybe a mistake use of `cmake_dependent_option`: https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html

**Comment by halx99** [comment]
Better solution is:

1. AXPlatform.cmake insert follow code at line:59
```cmake
if (NOT DEFINED WIN32)
    set(WIN32 FALSE)
endif()
```
3. `cmake_dependent_option(AX_USE_COMPAT_GL "Whether use compatibility GL as render backend" ${WIN32} "WIN32 OR APPLE" OFF)`

**Comment by rh101** [comment]
> 3\. cmake_dependent_option(AX_USE_COMPAT_GL "Whether use compatibility GL as render backend" ${WIN32} "WIN32 OR APPLE" OFF)

Oh! Yes that's a good solution.  I didn't notice that you could use conditional operators (the `OR`) inside the dependency section.

**Comment by smilediver** [comment]
Pushed the latest solution that was discussed.

**Review by halx99 — APPROVED** [review]

**Pull request merged**
