### PR TITLE
Update build.bat (for working on different axmol build settings)

### PR DESCRIPTION
**Pull request by aismann**
## Describe your changes
Controlling the axmol command over the env: AX_ROOT

## Issue ticket number and link
#1801

### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [x] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

**Comment by smilediver** [comment]
Having #1801 in mind, I think it's a bad direction to add more dependencies to `AX_ROOT` env variable.

**Comment by aismann** [comment]
> Having #1801 in mind, I think it's a bad direction to add more dependencies to `AX_ROOT` env variable.

AX_ROOT is only a 'place holder' for a path.
At the moment its the path env which is used to find the correct tool. 
Thats is not realy a good way

**Comment by aismann** [comment]
@halx99 
Is the ios build hanging?

**Comment by halx99** [comment]
> @halx99 Is the ios build hanging?

maybe cmake 3.29.0 random block infinitely

**Comment by aismann** [comment]
Solved with this changes committed in https://github.com/axmolengine/axmol/commit/197f2adfcd1e23b35f4520eeeccc655acdbe3356

**Pull request closed without merging**
