### PR TITLE
Add JobSystem support

### PR DESCRIPTION
**Pull request by halx99**
### For each PR
- [ ] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [ ] I have performed a self-review of my code.
       
   Optional:
   - [ ] I have checked readme and add important infos to this PR.
   - [ ] I have added/adapted some tests too.
          
### For core/new feature PR
- [ ] I have checked readme and add important infos to this PR.
- [ ] I have added thorough tests.

### CODE REVIEW

**Comment by smilediver** [comment]
Is `std::span` available on iOS and Android?

**Comment by halx99** [comment]
> Is `std::span` available on iOS and Android?

Yes, all ci passed.

**Comment by paulocoutinhox** [comment]
Hi,

Can you explain what is this? And the different between old mode?

Thanks.

**Comment by halx99** [comment]
It's more general, more customizable.

**Comment by iAndyHD3** [comment]
why no tests or documentation? it would make sense

**Pull request merged**
