### PR TITLE
templates: cpp: AppDelegate: Show stats only on debug mode

### PR DESCRIPTION
**Pull request by Roker2**
## Changes
I added code which exclude stats from screen on Release mode

## Checklist
- [x] Add Copyright if it missed:   
      - `"Copyright (c) 2019-present Axmol Engine contributors (see AUTHORS.md)."`
- [x] I have performed a self-review of my code.

### CODE REVIEW

**Comment by rh101** [comment]
We have to be careful when making changes like this to the template. The template should remain as simple as possible, and adding pre-processor checks like this in the template just adds "noise" to the code.

The template is meant as a starting point, and that file will be edited during the development process.  The developer of a project can easily add or delete any code they want to it, such as adding their own pre-processor checks if required.

**Comment by Roker2** [comment]
> We have to be careful when making changes like this to the template. The template should remain as simple as possible, and adding pre-processor checks like this in the template just adds "noise" to the code.
> 
> The template is meant as a starting point, and that file will be edited during the development process. The developer of a project can easily add or delete any code they want to it, such as adding their own pre-processor checks if required.

But this code can show that "Hey, you know, we have this thing and you can use it!". If it is not okay for you, you can close this PR.

**Comment by rh101** [comment]
> But this code can show that "Hey, you know, we have this thing and you can use it!". If it is not okay for you, you can close this PR.

Oh sorry, it's not about it being okay or not; it was just my opinion regarding changes like that.  

Also, the stats display can be used in release builds to monitor performance, which is why it was made to receive a boolean to turn it on or off. so it's not explicitly limited to debug mode.

**Comment by Roker2** [comment]
> > But this code can show that "Hey, you know, we have this thing and you can use it!". If it is not okay for you, you can close this PR.
> 
> Oh sorry, it's not about it being okay or not; it was just my opinion regarding changes like that.
> 
> Also, the stats display can be used in release builds to monitor performance, which is why it was made to receive a boolean to turn it on or off. so it's not explicitly limited to debug mode.

Hm. It have a sense. But I thought adding this `#if` will be useful... Okay, I think we can close this PR.

**Comment by halx99** [comment]
Thanks, close as @rh101  said

**Pull request closed without merging**
