### PR TITLE
fix scene, imports, comments and others

### PR DESCRIPTION
**Pull request by paulocoutinhox**
Which branch your pull-request should merge into?

- `dev`: Current 2.x BugFixs or Features
- `1.x`: 1.x BugFixs

## Describe your changes

- fix scene, imports, comments and others
- remove the use of cocos2d and use axmol
- keep the pattern filename/classname as same
- tested cpp/lua on ios/macos

## Checklist before requesting a review
-  [x] I have performed a self-review of my code.
-  [ ] If it is a core feature, I have added thorough tests.
-  [ ] I have checked readme and add important infos to this PR (if it needed).
-  [ ] I have added/adapted some tests too.

### CODE REVIEW

**Comment by rh101** [comment]
There changes in this PR which are not correct, and others, in my opinion, not necessary. I'll add a comment on each part separately.

@halx99 Please don't merge this in as it is.

**Comment by aismann** [comment]
Replacing ax::"Method()" with "Method()" is  no good idea.
@paulocoutinhox 
What is the reason?

Example:
image

**Comment by paulocoutinhox** [comment]
> Replacing ax::"Method()" with "Method()" is no good idea. @paulocoutinhox What is the reason?

Hi, in my opinion and code style, if we are importing namespace is because we don't want use namespace on every type. Don't make sense to me still prefix classes with namespaces if we already imported it.

**Comment by aismann** [comment]
> > Replacing ax::"Method()" with "Method()" is no good idea. @paulocoutinhox What is the reason?
> 
> Hi, in my opinion and code style, if we are importing namespace is because we don't want use namespace on every type. Don't make sense to me still prefix classes with namespaces if we already imported it.

Using a third party source which using also a `Size()` method like axmol => compiler does not know which one is meaning.

**Comment by rh101** [comment]
> Hi, in my opinion and code style, if we are importing namespace is because we don't want use namespace on every type. Don't make sense to me still prefix classes with namespaces if we already imported it.

That is a personal preference, and it's fine if you want to use that in your own code, but this specific file is part of the template, and making a change like this is forcing your personal preference on every other developer who is creating a project.

**Comment by paulocoutinhox** [comment]
> > > Replacing ax::"Method()" with "Method()" is no good idea. @paulocoutinhox What is the reason?
> > 
> > 
> > Hi, in my opinion and code style, if we are importing namespace is because we don't want use namespace on every type. Don't make sense to me still prefix classes with namespaces if we already imported it.
> 
> Using a third party source which using also a `Size()` method like axmol => compiler does not know which one is meaning.

I personally prefer to leave the project clean and less verbose and adjust external things to suit my project rather than leaving the project with things that are unnecessary for the context. It's better to use the prefix/namespace only where you really need it than having to use it for the majority of our code on a daily basis. If you have something external with the same name, then use it for what is external and not for the day-to-day code, which is most of it.

**Comment by paulocoutinhox** [comment]
> > Hi, in my opinion and code style, if we are importing namespace is because we don't want use namespace on every type. Don't make sense to me still prefix classes with namespaces if we already imported it.
> 
> That is a personal preference, and it's fine if you want to use that in your own code, but this specific file is part of the template, and making a change like this is forcing your personal preference on every other developer who is creating a project.

I understand, but each of you also has your preferences. I can't make a PR with mine? Are they worse? Is there any document here saying which code style should be followed?

**Comment by rh101** [comment]
> I personally prefer to leave the project clean and less verbose and adjust external things to suit my project rather than leaving the project with things that are unnecessary for the context. It's better to use the prefix/namespace only where you really need it than having to use it for the majority of our code on a daily basis. If you have something external with the same name, then use it for what is external and not for the day-to-day code, which is most of it.

> I understand, but each of you also has your preferences. I can't make a PR with mine? Are they worse? Is there any document here saying which code style should be followed?

Once again, personal preference should not be a factor in making changes to code that is used by others.  It's definitely not a good enough reason to make a change like this, because you are forcing your personal preferences on all other developers.

**Comment by rh101** [comment]
It was unnecessary to close this, because some changes made sense, such as changing `HelloWorld` to `HelloWorldScene`.  It's just the other changes needed addressing.

**Pull request closed without merging**
